# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: sdk
    version: 2.2.203
- script: dotnet --info
  displayName: Dump Info
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-configuration $(buildConfiguration) -target Pack'
    failOnStderr: true
  displayName: 'Build'
- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: 'artifacts/tests'
  displayName: 'Publish Test results'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: artifacts/tests/coverage.cobertura.xml
    failIfCoverageEmpty: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'artifacts/nuget'
    artifactName: 'Nuget'
    displayName: 'Publish Artifacts'
