# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- refs/tags/*

pr:
  autoCancel: true

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: sdk
    version: 3.0.100-preview4-011223
- script: dotnet --info
  displayName: Dump Info
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-configuration $(buildConfiguration) -target CI'
    failOnStderr: true
  displayName: 'Build'
- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: 'artifacts/tests'
  displayName: 'Publish Test results'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: artifacts/tests/coverage.cobertura.xml
    reportDirectory: artifacts/tests/Reports
    failIfCoverageEmpty: true
  displayName: 'Publish Code Coverage'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'artifacts/nuget'
    artifactName: 'Nuget'
  displayName: 'Publish Packages'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: Github-Beffyman
    repositoryName: $(Build.Repository.Name)
    action: create
    target: $(Build.SourceVersion)
    tagSource: manual
    title: $(GitVersion.NuGetVersion)
    assets: $(Build.ArtifactStagingDirectory)/**/*.nupkg
  displayName: 'Create Github Release'
  condition: contains(variables['Build.SourceBranch'], 'tags')
- task: NuGetCommand@2
  inputs:
    command: push
    feedsToUse: select
    vstsFeed: Nuget-Beffyman
    nuGetFeedType: internal
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/*.nupkg;
  displayName: 'Push Nuget Packages'
  condition: contains(variables['Build.SourceBranch'], 'tags')
- task: NuGetCommand@2
  inputs:
    command: push
    feedsToUse: select
    vstsFeed: Nuget-Beffyman
    nuGetFeedType: internal
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/*.snupkg;
  displayName: 'Push Nuget Symbol Packages'
  condition: contains(variables['Build.SourceBranch'], 'tags')