# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- refs/tags/*

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
    - src/*
    - tests/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Sdk'
  inputs:
    packageType: sdk
    useGlobalJson: true
    performMultiLevelLookup: true
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-configuration $(buildConfiguration) -target CI'
    failOnStderr: true
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: '$(Build.ArtifactStagingDirectory)/tests'
  displayName: 'Publish Test results'

- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(Build.ArtifactStagingDirectory)/tests/coverage.cobertura.xml
    #reportDirectory: $(Build.ArtifactStagingDirectory)/tests/Reports
    failIfCoverageEmpty: true
  displayName: 'Publish Code Coverage'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
    artifactName: 'Nuget'
  displayName: 'Publish Packages'